name = 'magellanic'
author = 'marsevilspirit'
baseURL = 'https://example.org/'
description = ''
languageCode = 'en-US'
license = 'MIT'
licenselink = "https://github.com/marsevilspirit/magellanic/blob/main/LICENSE"
title = 'My New Hugo Site'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
