name = "magellanic"
author = "marsevilspirit"
baseURL = "https://example.org/"
description = "marsevilspirit's blog"
languageCode = "en-US"
license = "MIT"
licenselink = "https://github.com/marsevilspirit/magellanic/blob/main/LICENSE"
title = "My New Hugo Site"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.146.0"

[menus]
  [[menus.main]]
    name = "posts"
    pageRef = "/posts"
    weight = 1

  [[menus.main]]
    name = "about"
    pageRef = "/about"
    weight = 2

[Params]
  logo = "logo"
  DateFormatList = "2006-01-02"

  [[Params.social]]
    name = "github"
    url = "https://github.com"
